image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - docker-push

build:
  stage: build
  script:
    - gradle clean build
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - build/libs

docker-push:
  image: centos:8
  stage: docker-push
  when: always
#  only:
#    refs:
#      - tags
#      - master
  before_script:
    - echo "In docker-push stage..."
    - yum update -y
  script:
    - pwd
    - cp build/libs/ewocsfhirapi*.jar docker_ewocs/ewocsfhirapi.jar
    - curl -fsSL https://get.docker.com/ | sh
    - systemctl enable docker
    - systemctl start docker
    - docker info