image: gradle:6.3.0-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - docker-push

build:
  stage: build
  script:
    - gradle clean build
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - build/libs

docker-push:
  stage: docker-push
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  when: always
#  only:
#    refs:
#      - tags
#      - master
  before_script:
    - echo "In docker-push stage..."
#    - yum update -y
  script:
    - docker info
    - docker login -u sglanger -p ThisIsEasy registry.hub.docker.com/sglanger/flowsigma_ewocs
    - docker pull registry.hub.docker.com/sglanger/flowsigma_ewocs
    - docker logout
