image: gradle:6.3.0-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - docker-push

build:
  stage: build
  script:
    - gradle clean build
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - build/libs
      - build/reports/tests/test/
      - build/test-results/test/

docker-push:
  stage: docker-push
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  when: always
  only:
    refs:
      - tags
      - master
  before_script:
    - echo "In docker build and push stage..."
# https://rollout.io/blog/using-docker-push-to-publish-images-to-dockerhub/
  script:
    - DOCKER_REPO=registry.hub.docker.com
    - IMG_NAME="${DOCKER_REPO}/sglanger/ewocs_fhir_api"
    - TAG=$CI_COMMIT_SHA
    - IMG_TAG=${IMG_NAME}:${TAG}
    - IMG_LATEST_TAG=${IMG_NAME}:latest
    - docker build --tag ${IMG_TAG} .
    - docker tag ${IMG_TAG} ${IMG_LATEST_TAG}
    - docker login -u sglanger -p ThisIsEasy ${DOCKER_REPO}
    - docker push ${IMG_NAME}
    - docker logout