server:
  port: 8009

spring:
  fhir:
    host: "http://hackathon.siim.org/fhir/"
    apiKey: "dd6f7f1d-1586-438f-8d35-ff589a12f4df"
  jackson:
    serialization:
      indent-output: true

logging:
  path: logs
  name: logs/fhir-api.log
  pattern:
    console: '%-5p [%d] [%-30logger{1}] %m%n%rEx{4}'
    file: '%-5p [%d] [%-30logger{1}] %m%n%rEx{4}'
  level:
    root: ERROR
    com.flowsigma: DEBUG
    org.springframework.web: WARN
  appenders:
    - type: console
      logFormat: '%-5p [%d] [%-30logger{1}] %m%n%rEx{4}'
    - type: file
      currentLogFilename: ./logs/fhirapi.log
      archivedLogFilenamePattern: ./logs/archive/fhirapi-%d.log.gz